class FlowerBouquet {
  final int flowerId;
  final int price;
  final String size;
  final double rating;
  final String category;
  final String temp;
  final String imageUrl;
  final String plantName;
  final int humidity;
  final bool isFavorated;
  final String description;

  FlowerBouquet({
    required this.flowerId,
    required this.price,
    required this.size,
    required this.rating,
    required this.category,
    required this.temp,
    required this.imageUrl,
    required this.humidity,
    required this.isFavorated,
    required this.description,
    required this.plantName,
  });

  static List<FlowerBouquet> flowerList = [
    FlowerBouquet(
      flowerId: 1,
      price: 20,
      size: 'Medium',
      rating: 4.5,
      category: 'Candy',
      temp: '18-24°C',
      imageUrl: 'assets/images/c1.png',
      humidity: 60,
      isFavorated: false,
      description: 'This is a beautiful Candy Bouqute with blue flowers.',
      plantName: 'Blue rose flower',
    ),
    FlowerBouquet(
      flowerId: 2,
      price: 15,
      size: 'Small',
      rating: 4.2,
      category: 'Sunflower',
      temp: '20-30°C',
      imageUrl: 'assets/images/s1.png',
      humidity: 70,
      isFavorated: true,
      description: 'This plant has colorful flowers and requires sunlight.',
      plantName: 'Colorful Flower Plant',
    ),
    FlowerBouquet(
      flowerId: 3,
      price: 25,
      size: 'Large',
      rating: 4.8,
      category: 'Rose',
      temp: '16-22°C',
      imageUrl: 'assets/images/r1.png',
      humidity: 65,
      isFavorated: true,
      description: 'This is a beautiful  Bouqute with blue flowers.',
      plantName: 'Blue rose flower',
    ),
    FlowerBouquet(
      flowerId: 4,
      price: 18,
      size: 'Small',
      rating: 3.9,
      category: 'Bridal',
      temp: '22-28°C',
      imageUrl: 'assets/images/b1.png',
      humidity: 75,
      isFavorated: false,
      description: 'This very nice  Bridal Bouquet .',
      plantName: 'Bridal Bouquet',
    ),
    FlowerBouquet(
      flowerId: 5,
      price: 30,
      size: 'Medium',
      rating: 4.6,
      category: 'Tulip',
      temp: '20-26°C',
      imageUrl: 'assets/images/t1.png',
      humidity: 55,
      isFavorated: true,
      description: 'This very nice  Tulip Bouquet .',
      plantName: 'Tulip Bouquet',
    ),
    FlowerBouquet(
      flowerId: 6,
      price: 20,
      size: 'Medium',
      rating: 4.5,
      category: 'Candy',
      temp: '18-24°C',
      imageUrl: 'assets/images/c2.png',
      humidity: 60,
      isFavorated: false,
      description: 'This is a beautiful Candy Bouqute with blue flowers.',
      plantName: 'Blue rose flower',
    ),
    FlowerBouquet(
      flowerId: 7,
      price: 15,
      size: 'Small',
      rating: 4.2,
      category: 'Sunflower',
      temp: '20-30°C',
      imageUrl: 'assets/images/s2.png',
      humidity: 70,
      isFavorated: true,
      description: 'This plant has colorful flowers and requires sunlight.',
      plantName: 'Colorful Flower Plant',
    ),
    FlowerBouquet(
      flowerId: 8,
      price: 25,
      size: 'Large',
      rating: 4.8,
      category: 'Rose',
      temp: '16-22°C',
      imageUrl: 'assets/images/r2.png',
      humidity: 65,
      isFavorated: true,
      description: 'This is a beautiful  Bouqute with blue flowers.',
      plantName: 'Blue rose flower',
    ),
    FlowerBouquet(
      flowerId: 9,
      price: 18,
      size: 'Small',
      rating: 3.9,
      category: 'Bridal',
      temp: '22-28°C',
      imageUrl: 'assets/images/b2.png',
      humidity: 75,
      isFavorated: false,
      description: 'This very nice  Bridal Bouquet .',
      plantName: 'Bridal Bouquet',
    ),
    FlowerBouquet(
      flowerId: 10,
      price: 30,
      size: 'Medium',
      rating: 4.6,
      category: 'Tulip',
      temp: '20-26°C',
      imageUrl: 'assets/images/t2.png',
      humidity: 55,
      isFavorated: true,
      description: 'This very nice  Tulip Bouquet .',
      plantName: 'Tulip Bouquet',
    ),
    FlowerBouquet(
      flowerId: 11,
      price: 20,
      size: 'Medium',
      rating: 4.5,
      category: 'Candy',
      temp: '18-24°C',
      imageUrl: 'assets/images/c3.png',
      humidity: 60,
      isFavorated: false,
      description: 'This is a beautiful Candy Bouqute with blue flowers.',
      plantName: 'Blue rose flower',
    ),
    FlowerBouquet(
      flowerId: 12,
      price: 15,
      size: 'Small',
      rating: 4.2,
      category: 'Sunflower',
      temp: '20-30°C',
      imageUrl: 'assets/images/s3.png',
      humidity: 70,
      isFavorated: true,
      description: 'This plant has colorful flowers and requires sunlight.',
      plantName: 'Colorful Flower Plant',
    ),
    FlowerBouquet(
      flowerId: 13,
      price: 25,
      size: 'Large',
      rating: 4.8,
      category: 'Rose',
      temp: '16-22°C',
      imageUrl: 'assets/images/r3.png',
      humidity: 65,
      isFavorated: true,
      description: 'This is a beautiful  Bouqute with blue flowers.',
      plantName: 'Blue rose flower',
    ),
    FlowerBouquet(
      flowerId: 14,
      price: 18,
      size: 'Small',
      rating: 3.9,
      category: 'Bridal',
      temp: '22-28°C',
      imageUrl: 'assets/images/b3.png',
      humidity: 75,
      isFavorated: false,
      description: 'This very nice  Bridal Bouquet .',
      plantName: 'Bridal Bouquet',
    ),
    FlowerBouquet(
      flowerId: 15,
      price: 30,
      size: 'Medium',
      rating: 4.6,
      category: 'Tulip',
      temp: '20-26°C',
      imageUrl: 'assets/images/t3.png',
      humidity: 55,
      isFavorated: true,
      description: 'This very nice  Tulip Bouquet .',
      plantName: 'Tulip Bouquet',
    ),
    FlowerBouquet(
      flowerId: 16,
      price: 20,
      size: 'Medium',
      rating: 4.5,
      category: 'Candy',
      temp: '18-24°C',
      imageUrl: 'assets/images/c4.png',
      humidity: 60,
      isFavorated: false,
      description: 'This is a beautiful Candy Bouqute with blue flowers.',
      plantName: 'Blue rose flower',
    ),
    FlowerBouquet(
      flowerId: 17,
      price: 15,
      size: 'Small',
      rating: 4.2,
      category: 'Sunflower',
      temp: '20-30°C',
      imageUrl: 'assets/images/s4.png',
      humidity: 70,
      isFavorated: true,
      description: 'This plant has colorful flowers and requires sunlight.',
      plantName: 'Colorful Flower Plant',
    ),
    FlowerBouquet(
      flowerId: 18,
      price: 25,
      size: 'Large',
      rating: 4.8,
      category: 'Rose',
      temp: '16-22°C',
      imageUrl: 'assets/images/r4.png',
      humidity: 65,
      isFavorated: true,
      description: 'This is a beautiful  Bouqute with blue flowers.',
      plantName: 'Blue rose flower',
    ),
    FlowerBouquet(
      flowerId: 19,
      price: 18,
      size: 'Small',
      rating: 3.9,
      category: 'Bridal',
      temp: '22-28°C',
      imageUrl: 'assets/images/b4.png',
      humidity: 75,
      isFavorated: false,
      description: 'This very nice  Bridal Bouquet .',
      plantName: 'Bridal Bouquet',
    ),
    FlowerBouquet(
      flowerId: 20,
      price: 30,
      size: 'Medium',
      rating: 4.6,
      category: 'Tulip',
      temp: '20-26°C',
      imageUrl: 'assets/images/t4.png',
      humidity: 55,
      isFavorated: true,
      description: 'This very nice  Tulip Bouquet .',
      plantName: 'Tulip Bouquet',
    ),
    FlowerBouquet(
      flowerId: 21,
      price: 20,
      size: 'Medium',
      rating: 4.5,
      category: 'Candy',
      temp: '18-24°C',
      imageUrl: 'assets/images/c5.png',
      humidity: 60,
      isFavorated: false,
      description: 'This is a beautiful Candy Bouqute with blue flowers.',
      plantName: 'Blue rose flower',
    ),
    FlowerBouquet(
      flowerId: 22,
      price: 15,
      size: 'Small',
      rating: 4.2,
      category: 'Sunflower',
      temp: '20-30°C',
      imageUrl: 'assets/images/s5.png',
      humidity: 70,
      isFavorated: true,
      description: 'This plant has colorful flowers and requires sunlight.',
      plantName: 'Colorful Flower Plant',
    ),
    FlowerBouquet(
      flowerId: 23,
      price: 25,
      size: 'Large',
      rating: 4.8,
      category: 'Rose',
      temp: '16-22°C',
      imageUrl: 'assets/images/r5.png',
      humidity: 65,
      isFavorated: true,
      description: 'This is a beautiful  Bouqute with blue flowers.',
      plantName: 'Blue rose flower',
    ),
    FlowerBouquet(
      flowerId: 24,
      price: 18,
      size: 'Small',
      rating: 3.9,
      category: 'Bridal',
      temp: '22-28°C',
      imageUrl: 'assets/images/b5.png',
      humidity: 75,
      isFavorated: false,
      description: 'This very nice  Bridal Bouquet .',
      plantName: 'Bridal Bouquet',
    ),
    FlowerBouquet(
      flowerId: 25,
      price: 30,
      size: 'Medium',
      rating: 4.6,
      category: 'Tulip',
      temp: '20-26°C',
      imageUrl: 'assets/images/t5.png',
      humidity: 55,
      isFavorated: true,
      description: 'This very nice  Tulip Bouquet .',
      plantName: 'Tulip Bouquet',
    ),
  ];
}
