class Plant {
  final int plantId;
  final int price;
  final String size;
  final double rating;
  final String category;
  final String temp;
  final String imageUrl;
  final String plantName;
  final int humidity;
  final bool isFavorated;
  final String description;

  Plant({
    required this.plantId,
    required this.price,
    required this.size,
    required this.rating,
    required this.category,
    required this.temp,
    required this.imageUrl,
    required this.humidity,
    required this.isFavorated,
    required this.description,
    required this.plantName,
  });

  static List<Plant> plantList = [
  Plant(
    plantId: 1,
    price: 20,
    size: 'Medium',
    rating: 4.5,
    category: 'Indoor',
    temp: '18-24°C',
    imageUrl: 'assets/images/test.png',
    humidity: 60,
    isFavorated: false,
    description: 'This is a beautiful plant with green leaves.',
    plantName: 'Green Leaf Plant',
  ),
  Plant(
    plantId: 2,
    price: 15,
    size: 'Small',
    rating: 4.2,
    category: 'Outdoor',
    temp: '20-30°C',
    imageUrl:  'assets/images/splashone.png',
    humidity: 70,
    isFavorated: true,
    description: 'This plant has colorful flowers and requires sunlight.',
    plantName: 'Colorful Flower Plant',
  ),
  Plant(
    plantId: 3,
    price: 25,
    size: 'Large',
    rating: 4.8,
    category: 'Supplement',
    temp: '16-22°C',
    imageUrl:  'assets/images/splashthree.png',
    humidity: 65,
    isFavorated: true,
    description: 'This plant has tall stems and needs partial shade.',
    plantName: 'Tall Stem Plant',
  ),
  Plant(
    plantId: 4,
    price: 18,
    size: 'Small',
    rating: 3.9,
    category: 'Garden',
    temp: '22-28°C',
    imageUrl:  'assets/images/splashtwo.png',
    humidity: 75,
    isFavorated: false,
    description: 'This plant is drought-tolerant and has succulent leaves.',
    plantName: 'Succulent Plant',
  ),
  Plant(
    plantId: 5,
    price: 30,
    size: 'Medium',
    rating: 4.6,
    category: 'Supplement',
    temp: '20-26°C',
    imageUrl:  'assets/images/1.png',
    humidity: 55,
    isFavorated: true,
    description: 'This plant has variegated leaves and requires indirect light.',
    plantName: 'Variegated Leaf Plant',
  ),
  Plant(
    plantId: 6,
    price: 12,
    size: 'Small',
    rating: 4.1,
    category: 'Outdoor',
    temp: '18-25°C',
    imageUrl:  'assets/images/2.png',
    humidity: 70,
    isFavorated: false,
    description: 'This plant produces aromatic flowers and attracts butterflies.',
    plantName: 'Aromatic Flower Plant',
  ),
  Plant(
    plantId: 7,
    price: 35,
    size: 'Large',
    rating: 4.9,
    category: 'Garden',
    temp: '16-20°C',
    imageUrl:  'assets/images/3.png',
    humidity: 60,
    isFavorated: true,
    description: 'This plant has large leaves and thrives in low light conditions.',
    plantName: 'Low Light Plant',
  ),
  Plant(
    plantId: 8,
    price: 22,
    size: 'Medium',
    rating: 4.3,
    category: 'Supplement',
    temp: '22-30°C',
    imageUrl:  'assets/images/4.png',
    humidity: 75,
    isFavorated: true,
    description: 'This plant is known for its vibrant and long-lasting blooms.',
    plantName: 'Bloomful Plant',
  ),
  Plant(
    plantId: 9,
    price: 17,
    size: 'Small',
    rating: 3.7,
    category: 'Indoor',
    temp: '18-24°C',
    imageUrl:  'assets/images/5.png',
    humidity: 55,
    isFavorated: false,
    description: 'This plant has delicate foliage and requires high humidity.',
    plantName: 'Delicate Foliage Plant',
  ),
  Plant(
    plantId: 10,
    price: 28,
    size: 'Large',
    rating: 4.7,
    category: 'Garden',
    temp: '20-28°C',
    imageUrl:  'assets/images/6.png',
    humidity: 65,
    isFavorated: true,
    description: 'This plant is a climbing vine and adds a tropical touch to any space.',
    plantName: 'Climbing Vine Plant',
  ),

];

}
